logiSpawner addAction ["Spawn Fuel Truck", "scripts\refuel_veh.sqf"];
logiSpawner addAction ["Spawn Ammo Truck", "scripts\rearm_veh.sqf"];
logiSpawner addAction ["Spawn Repair Truck", "scripts\repair_veh.sqf"];
logiSpawner addAction ["Spawn BTR Heavy", "scripts\btr_80_veh.sqf"];
logiSpawner addAction ["Spawn BMP", "scripts\bmp_2_veh.sqf"];
logiSpawner addAction ["Spawn M2A2", "scripts\m2a2_veh.sqf"];
logiSpawner addAction ["Spawn LAV", "scripts\lav_25a1_veh.sqf"];
logiSpawner addAction ["Spawn T-72", "scripts\t_72a_veh.sqf"];
logiSpawner addAction ["Spawn Towing Tractor", "scripts\towingtractor_veh.sqf"];
logiSpawner addAction ["Spawn Ural", "scripts\ural_veh.sqf"];
logiSpawner addAction ["Spawn Metal Gear", "scripts\ikarusbus_veh.sqf"];